services:
  postgres:
    image: postgres:16-alpine
    container_name: rekberinsaja-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: rekber
      POSTGRES_PASSWORD: rekber123
      POSTGRES_DB: rekberinsaja
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
