version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: rekber_postgres
    restart: always
    environment:
      POSTGRES_USER: rekber
      POSTGRES_PASSWORD: rekber123
      POSTGRES_DB: rekberinsaja
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
