/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#38debb",
        "on-tertiary-container": "#3a4365",
        "secondary": "#a2e7ff",
        "on-tertiary-fixed": "#0f1a39",
        "on-secondary": "#003642",
        "surface-tint": "#38debb",
        "on-surface-variant": "#bacac3",
        "surface-container": "#171f32",
        "tertiary-fixed": "#dce1ff",
        "secondary-fixed": "#b4ebff",
        "outline": "#85948e",
        "on-error-container": "#ffdad6",
        "surface-container-highest": "#2d3448",
        "surface-container-low": "#131b2d",
        "on-background": "#dbe2fb",
        "on-tertiary": "#252f50",
        "tertiary-container": "#a7b1d9",
        "on-primary-container": "#004e40",
        "tertiary": "#c3ccf6",
        "primary": "#44e5c2",
        "on-secondary-container": "#005669",
        "inverse-surface": "#dbe2fb",
        "primary-fixed": "#5ffbd6",
        "primary-container": "#00c9a7",
        "on-primary": "#00382d",
        "surface-bright": "#31394c",
        "surface": "#0b1325",
        "on-secondary-fixed": "#001f27",
        "surface-container-lowest": "#060e1f",
        "surface-container-high": "#222a3d",
        "tertiary-fixed-dim": "#bbc5ee",
        "secondary-fixed-dim": "#3cd7ff",
        "on-primary-fixed": "#002019",
        "inverse-primary": "#006b58",
        "error-container": "#93000a",
        "on-secondary-fixed-variant": "#004e5f",
        "on-primary-fixed-variant": "#005142",
        "surface-dim": "#0b1325",
        "secondary-container": "#00d2fd",
        "outline-variant": "#3c4a45",
        "on-surface": "#dbe2fb",
        "on-tertiary-fixed-variant": "#3c4567",
        "inverse-on-surface": "#283043",
        "on-error": "#690005",
        "error": "#ffb4ab",
        "surface-variant": "#2d3448",
        "background": "#0b1325"
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"],
        "mono": ["JetBrains Mono"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
